der_program_list:
  - mRID: E0000001
    default_der_control: True
    description: Default DERC
    DERControlBase:
      opModMaxLimW: 10000
      setGradW: 0
      setSoftGradW: 0
  - mRID: E0000002
    description: Blah blah blah
    # links to control stuff here??
    primacy: 89
